In [5]:
import numpy as nf


In [7]:
import numpy as nk
print(nk.__version__)

1.23.5


In [8]:
import numpy as np
arr = np.array([101, 201, 301, 401, 501])
print(arr)
print(type(arr))

[101 201 301 401 501]
<class 'numpy.ndarray'>


In [10]:
import numpy as np

nameList = ['Angel', "Shemi", "Marvel", "Linda"]

ageTuple = (41, 32, 21, 19)

gradeDict = {"CSC102": 89, "MTH 102": 77, "CHM 102": 69, "GST 102": 99}

arr_nameList = np.array(nameList)

arr_ageTuple = np.array(ageTuple)

arr_gradeDict = np.array(gradeDict)

print(arr_nameList)
print(arr_ageTuple)
print(arr_gradeDict)

['Angel' 'Shemi' 'Marvel' 'Linda']
[41 32 21 19]
{'CSC102': 89, 'MTH 102': 77, 'CHM 102': 69, 'GST 102': 99}


In [13]:
import numpy as np

classNum = int(input("How many students are in the CSC 102 class?"))

class_arr = np.array(classNum)

if (class_arr == 1):
    print("There is only ", class_arr, "student in CSC 102 class" )
else:
    print("There are", class_arr, "students in CSC 102 class" )

How many students are in the CSC 102 class?90
There are 90 students in CSC 102 class


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [18]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [24]:
import numpy as np

a = np.array([42])
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 2, 3, 4, 5])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
3
2
1
